[functions]
  node_bundler = "esbuild"

[functions.videos]
  external_node_modules = ["googleapis"]
  included_files = ["netlify/functions/googleapi-keys*.json"]

[functions.subscriptions]
  external_node_modules = ["googleapis"]
  included_files = ["netlify/functions/googleapi-keys*.json"]